name: Solid presentation

on:
  push:
    branches: [ master ]

jobs:
  build-presentation:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: librsvg2-bin
        version: 1.0
    - name: pdflatex
      uses: xu-cheng/latex-action@v3
      with:
        root_file: solid.tex
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: solid.pdf
